services:
  - type: web
    name: project-09
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend render_app:app
    healthCheckPath: /health
    autoDeploy: true
